language: python
sudo: required
dist: xenial
python: '3.6.6'

cache:
  - pip

env:
  - APP_SETTINGS=TestingConfig

before_install:
  - 

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make test

after_success:
  - pipenv run codecov

branches:
  only:
    - master
