language: python
sudo: required
dist: xenial
python: '3.6'

cache:
  - pip

env:
  - APP_SETTINGS=TestingConfig
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make test

after_success:
  - pipenv run codecov

branches:
  only:
    - master
